### ISSUE TITLE
Error parsing record for TLD queries

### ISSUE THREAD

**Issue by mckern** [likexian/whois-parser-go#14]
👋 ! Thanks for this library -- it's been very useful to me as I've been building out [spiry](https://github.com/mckern/spiry/) but I found a show-stopping bug while updating my dependency on it (in the hopes of not using a vendored/forked copy of whois-parser-go any longer).

# The problem

BSD and GNU `whois` clients (and the IANA whois resolver) support looking up the canonical resolver for a given TLD (country code or otherwise):

```
$ whois -h whois.iana.org .edu
% IANA WHOIS server
% for more information on IANA, visit http://www.iana.org
% This query returned 1 object

domain:       EDU

organisation: EDUCAUSE
address:      282 Century Place, Suite 5000
address:      Louisville, CO  80027
address:      United States

contact:      administrative
name:         Information Services Administration
organisation: EDUCAUSE
address:      4772 Walnut Street, Suite 206
address:      Boulder Colorado 80301
address:      United States
phone:        +1-303-449-4430
fax-no:       +1-303-440-0461
e-mail:       netadmin@educause.edu

contact:      technical
name:         Registry Customer Service
organisation: VeriSign Global Registry
address:      12061 Bluemont Way
address:      Reston Virginia 20190
address:      United States
phone:        +1-703-925-6999
fax-no:       +1-703-948-3978
e-mail:       info@verisign-grs.com

nserver:      A.EDU-SERVERS.NET 192.5.6.30 2001:503:a83e:0:0:0:2:30
nserver:      B.EDU-SERVERS.NET 192.33.14.30 2001:503:231d:0:0:0:2:30
nserver:      C.EDU-SERVERS.NET 192.26.92.30 2001:503:83eb:0:0:0:0:30
nserver:      D.EDU-SERVERS.NET 192.31.80.30 2001:500:856e:0:0:0:0:30
nserver:      E.EDU-SERVERS.NET 192.12.94.30 2001:502:1ca1:0:0:0:0:30
nserver:      F.EDU-SERVERS.NET 192.35.51.30 2001:503:d414:0:0:0:0:30
nserver:      G.EDU-SERVERS.NET 192.42.93.30 2001:503:eea3:0:0:0:0:30
nserver:      H.EDU-SERVERS.NET 192.54.112.30 2001:502:8cc:0:0:0:0:30
nserver:      I.EDU-SERVERS.NET 192.43.172.30 2001:503:39c1:0:0:0:0:30
nserver:      J.EDU-SERVERS.NET 192.48.79.30 2001:502:7094:0:0:0:0:30
nserver:      K.EDU-SERVERS.NET 192.52.178.30 2001:503:d2d:0:0:0:0:30
nserver:      L.EDU-SERVERS.NET 192.41.162.30 2001:500:d937:0:0:0:0:30
nserver:      M.EDU-SERVERS.NET 192.55.83.30 2001:501:b1f9:0:0:0:0:30
ds-rdata:     28065 8 2 4172496CDE85534E51129040355BD04B1FCFEBAE996DFDDE652006F6F8B2CE76

whois:        whois.educause.edu

status:       ACTIVE
remarks:      Registration information:
remarks:      http://www.educause.edu/edudomain

created:      1985-01-01
changed:      2018-10-16
source:       IANA
```

But using [whois-parser-go 1.9.0](https://github.com/likexian/whois-parser-go/tree/v1.9.0) I recieve the following error when I try to resolve a TLD:

```
Domain whois data invalid.
```

## Reproduction case

Here's some example code to reproduce the problem:

```go
package main

import (
	"fmt"

	"github.com/likexian/whois-go"
	whoisparser "github.com/likexian/whois-parser-go"
)

func main() {
	resolver := "whois.iana.org"
	tld := "com"
	record, err := whois.Whois(tld, resolver)

	fmt.Printf("raw record: %+v\nerror: %+v\n\n",
		record, err)

	result, err := whoisparser.Parse(record)
	fmt.Printf("resolver: %+v\nerror: %+v\n",
		result.Domain.WhoisServer, err)
}
```

I've tracked the problem down to this instruction (https://github.com/likexian/whois-parser-go/blob/master/parser.go#L223), from this commit: https://github.com/likexian/whois-parser-go/commit/e0a4accab8ef93d57c256f2bec705c4697e82642

This functionality worked previously so this is a new bug. It looks like there's an assumption that every whois record will contain a domain name, but that's not always going to be true -- top-level domain records appear to only list the bare TLD in the `domain` field.

# Oh also while I'm here

I also noticed that it looks like you're using regular expressions to match domain roots and top-level extensions -- have you considered using a library like https://godoc.org/golang.org/x/net/publicsuffix to do this instead? That page goes into more detail about the difficulty of the problem and how companies like Mozilla have solved it.

I'm happy to help with these bugs, but I didn't know if you were already working on anything related to these and didn't want to duplicate effort if you already had something in mind.

Thanks!

**Comment by likexian** [comment]
Hello @mckern 
Thanks for your feedback, I have fixed this issue.
Please update to the latest version and have a try.

The code below works for me:

```go
package main

import (
	"fmt"

	"github.com/likexian/whois-go"
	whoisparser "github.com/likexian/whois-parser-go"
)

func main() {
	tld := "com"
	record, err := whois.Whois(tld)

	fmt.Printf("raw record: %+v\nerror: %+v\n\n",
		record, err)

	result, err := whoisparser.Parse(record)
	fmt.Printf("resolver: %+v\nerror: %+v\n",
		result.Domain.WhoisServer, err)
}
```

**Comment by mckern** [comment]
Confirmed that this appears to be resolved now. Thanks!
