### ISSUE TITLE
Binary tools

### ISSUE THREAD

**Issue by mhf-ir** [likexian/whois-parser-go#15]
I think binary tools via json output will be awesome.

**Comment by likexian** [comment]
Hello @mhf-ir 
Thanks for your feedback, I will implment it.

**Comment by likexian** [comment]
Hello @mhf-ir 
The binary tool has been released, please have a try follow the link: https://github.com/likexian/whois-go/blob/master/cmd/whois/README.md

---
*If you think this repository is helpful, please share it with friends, thanks.*
