### ISSUE TITLE
Not correct parse whois from .ro domains

### ISSUE THREAD

**Issue by mrqwer88** [likexian/whois-parser-go#2]
Hello!

I try parsed **.ro** domain with  - 

```
package main

import (
    "fmt"
    "github.com/likexian/whois-go"
    "github.com/likexian/whois-parser-go"
)

func main() {

    domain := "avendo.ro"

    whoisResult_raw, err := whois.Whois(domain)
    if err != nil {
        panic(err)
    }
    whoisResult, err := whois_parser.Parser(whoisResult_raw)
    if err != nil {
        panic(err)
    }
    fmt.Println(domain, " - ", whoisResult.Registrar.NameServers)
    fmt.Println(whoisResult_raw)
    fmt.Println(whoisResult)

}
```

In result most fields are empty - 

```
go run check_whois_parse_for_ro_zone.go 
avendo.ro  -  

% Whois Server Version 3.0 - whois.rotld.ro:43

% Rights restricted by copyright.
% Specifically, this data MAY ONLY be used for Internet operational
% purposes. It may not be used for targeted advertising or any
% other purpose.

% Este INTERZISA folosirea datelor de pe acest server in oricare
% alt scop decat operarea retelei. In special este INTERZISA
% folosirea lor in scopuri publicitare.

% Top Level Domain : ro
% Maintainance : www.rotld.ro

  Domain Name: avendo.ro
  Registered On: 2013-07-25
  Registrar: ICI - ROTLD
  Referral URL: http://www.rotld.ro

  Nameserver: ns4.fastvps.ru
  Nameserver: ns3.fastvps.ru
  Nameserver: ns1.fastvps.ru
  Nameserver: ns2.fastvps.ru

  Domain Status: OK



{{ ICI - ROTLD  http://www.rotld.ro  avendo.ro ok   2013-07-25  } {             } {             } {             } {             }}
```

**Comment by b4dnewz** [comment]
same for .it domains

**Comment by likexian** [comment]
Hello, for .ro domain, the whois info provide nothing about registrant, so the function return nothing.

**Comment by likexian** [comment]
And for .it, this format is not supported now.

**Comment by jackale00** [comment]
Hi @likexian , do you plan to add support for other tld like .it, .de ?

**Comment by likexian** [comment]
Ok, I will think of it.

**Comment by mrqwer88** [comment]
> for .ro domain, the whois info provide nothing about registrant, so the function return nothing.

It is ok, but original question was about NameServers - it was in whois output, but not in parsed result.

**Comment by wingsuitist** [comment]
How would you integrate support for .ch and .de domain parsing?

**Comment by likexian** [comment]
> > for .ro domain, the whois info provide nothing about registrant, so the function return nothing.
> 
> It is ok, but original question was about NameServers - it was in whois output, but not in parsed result.
> But it seems I didn’t describe it very well, when create issue.

Hello @mrqwer88 , this has been fixed at a37d88d, please have a try.
Sorry for the misunderstanding and delay.

**Comment by likexian** [comment]
@moorada @wingsuitist 
Would you please provides a example of .de domain whois data?

**Comment by mrqwer88** [comment]
> > > for .ro domain, the whois info provide nothing about registrant, so the function return nothing.
> > 
> > 
> > It is ok, but original question was about NameServers - it was in whois output, but not in parsed result.
> > But it seems I didn’t describe it very well, when create issue.
> 
> Hello @mrqwer88 , this has been fixed at [a37d88d](https://github.com/likexian/whois-parser-go/commit/a37d88dc46b504ab1bd05718c1568afebe3284af), please have a try.
> Sorry for the misunderstanding and delay.

Yes - it work now, thanks!

**Comment by likexian** [comment]
> same for .it domains

Hello @b4dnewz 
.it domain is supported, please have a try.

**Comment by likexian** [comment]
> Hi @likexian , do you plan to add support for other tld like .it, .de ?

Hello moorada
.it and .de is supported, please have a try.

**Comment by likexian** [comment]
> How would you integrate support for .ch and .de domain parsing?

Hello @wingsuitist 
`.ch` and `.de` is supported, please have a try.
