### ISSUE TITLE
Struct omitempty tag

### ISSUE THREAD

**Issue by theblackturtle** [likexian/whois-parser-go#22]
Hi, I will be nice if you add `omitempty` tag to struct because when you encode struct to JSON, it will ignore the empty value.This make the output shorter and easier to view.

**Comment by likexian** [comment]
Thanks for you suggest, I will add it soon.

**Comment by likexian** [comment]
Hello @theblackturtle 
This has been released, please try the latest version.

---
*If you think this repository is helpful, please share it with friends, thanks.*
