### ISSUE TITLE
Does not parse whois information for .co.uk domains

### ISSUE THREAD

**Issue by KirksFletcher** [likexian/whois-parser-go#30]
As in the title, this package does not work with .co.uk domains at all. Ran over a list of 2000 domains and no .co.uk whois was able to be parsed. Everything else seemed ok. .co.uk is a really big one to miss!

**Comment by KirksFletcher** [comment]
Correction! I realized that some.co.uk and .com.au domain do not provide expiry dates in the whois information. Is there another way to get these?

**Comment by likexian** [comment]
> Correction! I realized that some.co.uk and .com.au domain do not provide expiry dates in the whois information. Is there another way to get these?

Sorry, I don't know about it.
